### ISSUE TITLE
Empty subject

### ISSUE THREAD

**Issue by Estecka** [Glagan/42-exam-rank-06#1]
Hi,

The file `subject.en.txt` is empty. 
Did you forget to add it in, or did you not have access to that subject in the first place ?

**Comment by Glagan** [comment]
Hi, I never had access to the *real* subject since you don't have any report after an exam anymore, and I guess I never bothered to write it by memory.

Since I passed the exam I can't do it anymore, so unless someone try and make a pull request with it, it will never be available, sorry.
